#HATS Collection
obs_collection=memray_runs_1
hats_primary_table_url=memray_runs_1
hats_builder=lsdb v0.6.6, hats v0.6.6
hats_creation_date=2025-10-09T22:47UTC
hats_estsize=12825
hats_release_date=2024-09-18
hats_version=v0.1
